site_name: Yale Center for Research Computing

theme:
    name: material
    custom_dir: 'theme'
    primary: '#0e4c92'
    accent: '#0e4c92'
    logo:
        icon: 'library_books'
    favicon: '/assets/images/favicon.ico'

    feature:
        tabs: true

extra_css:
    - 'stylesheets/extra.css'

extra_javascript:
    - 'js/extra.js'

markdown_extensions:
    - admonition
    - codehilite
    - pymdownx.details
    - pymdownx.keys
    - attr_list

nav:
    - Support:
        - index.md
        - Clusters at Yale:
            - clusters-at-yale/index.md
            - Request an Account: https://research.computing.yale.edu/account-request
            - clusters-at-yale/troubleshoot.md
            - Access the Clusters:
                - clusters-at-yale/access/index.md
                - clusters-at-yale/access/vpn.md
                - clusters-at-yale/access/mfa.md
                - clusters-at-yale/access/x11.md
                - clusters-at-yale/access/vnc.md
            - Applications & Software:
                - clusters-at-yale/applications/index.md
                - clusters-at-yale/applications/modules.md
                - Guides:
                    - clusters-at-yale/applications/guides/index.md
                    - clusters-at-yale/applications/guides/conda.md
                    - clusters-at-yale/applications/guides/singularity.md
                    - clusters-at-yale/applications/guides/tmux.md
            - Job Scheduling:
                - clusters-at-yale/job-scheduling/index.md
                - clusters-at-yale/job-scheduling/slurm.md
                - clusters-at-yale/job-scheduling/resource-requests.md
                - clusters-at-yale/job-scheduling/fairshare.md
                - clusters-at-yale/job-scheduling/dsq.md
                - clusters-at-yale/job-scheduling/slurm-examples.md
            - Data & Storage:
                - clusters-at-yale/data/index.md
                - clusters-at-yale/data/cluster-storage.md
                - Transfer Data: clusters-at-yale/data/transfer.md
            - The Clusters:
                - clusters-at-yale/clusters/index.md
                - Grace: clusters-at-yale/clusters/grace.md
                - clusters-at-yale/clusters/farnam.md
                - Ruddle: clusters-at-yale/clusters/ruddle.md
                - Milgram: clusters-at-yale/clusters/milgram.md